# Generated by Django 5.0.3 on 2024-05-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=9)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=7)),
                ('idOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordemServico.cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('total', models.FloatField()),
                ('observation', models.TextField()),
                ('serviceDate', models.DateTimeField()),
                ('idCar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordemServico.carro')),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordemServico.cadastro')),
            ],
        ),
    ]
